version: '3'

services:
  php:
    image: php:7.3-fpm
    networks:
      - lnmp
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./application/:/var/www/application/
      - ./extend/:/var/www/extend/
      - ./config/:/var/www/config/
      - ./public/:/var/www/public/
      - ./runtime/:/var/www/runtime/
      - ./route/:/var/www/route/
      - ./thinkphp/:/var/www/thinkphp/
      - ./vendor/:/var/www/vendor/
      - ./build.php:/var/www/build.php
      - ./think:/var/www/think
      - ./composer.json:/var/www/composer.json
      - ./php/:/usr/local/etc/php/
        #这个地方必须单独映射，因为SESSION本地会被忽略。加/强制映射为文件夹,如果不加session_path，SESSION将会失效
      - ./php/session_path/:/usr/local/etc/php/session_path
    environment:
      - TZ=Asia/Shanghai
      - APP_ENV=local
      - APP_DEBUG=ture
      #   MYSQL 设置
      - MYSQL_HOST=mysql
      - MYSQL_DB=lea5.1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=cgland2019
      - MYSQL_PORT=3306
  nginx:
    image: nginx:1.15.12
    networks:
      - lnmp
    ports: 
      - 8080:8080
    restart: always
    depends_on:
      - php
    volumes:
      - ./application/:/usr/share/nginx/application/
      - ./config/:/usr/share/nginx/config/
      - ./extend/:/usr/share/nginx/extend/
      - ./public/:/usr/share/nginx/public/
      - ./runtime/:/usr/share/nginx/runtime/
      - ./route/:/usr/share/nginx/route/
      - ./thinkphp/:/usr/share/nginx/thinkphp/
      - ./vendor/:/usr/share/nginx/vendor/
      - ./build.php/:/usr/share/nginx/build.php
      - ./think/:/usr/share/nginx/think/
      - ./nginx/:/etc/nginx/
  mysql:
    hostname: mysql
    image: mysql:8.0
    ports:
      - 3309:3306
    networks:
      - lnmp
    volumes:
      - ./mysql/conf/:/etc/mysql/
      - ./mysql/init.d/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: cgland2019

networks:
  lnmp:
